# Generated by Django 5.2.1 on 2026-06-19 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalseoaudit',
            name='gsc_country_filter',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='technicalseoaudit',
            name='gsc_device_filter',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='technicalseoaudit',
            name='gsc_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicalseoaudit',
            name='gsc_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='technicalseoaudit',
            name='gsc_inspections_found',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technicalseoaudit',
            name='gsc_rows_found',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technicalseoaudit',
            name='gsc_site_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='technicalseoaudit',
            name='gsc_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicalseoaudit',
            name='gsc_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='TechnicalSEOSearchConsoleRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(blank=True, max_length=1000)),
                ('query', models.CharField(blank=True, max_length=500)),
                ('device', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('clicks', models.FloatField(default=0)),
                ('impressions', models.FloatField(default=0)),
                ('ctr', models.FloatField(default=0)),
                ('position', models.FloatField(default=0)),
                ('date_range_start', models.DateField(blank=True, null=True)),
                ('date_range_end', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gsc_rows', to='technical_seo.technicalseoaudit')),
            ],
            options={
                'ordering': ['-clicks', '-impressions', 'position'],
                'indexes': [models.Index(fields=['audit', '-clicks'], name='technical_s_audit_i_ece2ce_idx'), models.Index(fields=['audit', 'page_url'], name='technical_s_audit_i_4ca28a_idx'), models.Index(fields=['audit', 'query'], name='technical_s_audit_i_ba122c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TechnicalSEOURLInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_url', models.URLField(max_length=1000)),
                ('verdict', models.CharField(blank=True, max_length=100)),
                ('coverage_state', models.CharField(blank=True, max_length=255)),
                ('indexing_state', models.CharField(blank=True, max_length=100)),
                ('robots_txt_state', models.CharField(blank=True, max_length=100)),
                ('page_fetch_state', models.CharField(blank=True, max_length=100)),
                ('google_canonical', models.URLField(blank=True, max_length=1000)),
                ('user_canonical', models.URLField(blank=True, max_length=1000)),
                ('last_crawl_time', models.DateTimeField(blank=True, null=True)),
                ('mobile_usability_verdict', models.CharField(blank=True, max_length=100)),
                ('rich_results_verdict', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gsc_url_inspections', to='technical_seo.technicalseoaudit')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gsc_inspections', to='technical_seo.technicalseopage')),
            ],
            options={
                'ordering': ['inspection_url'],
                'indexes': [models.Index(fields=['audit', 'verdict'], name='technical_s_audit_i_4da709_idx'), models.Index(fields=['audit', 'inspection_url'], name='technical_s_audit_i_a607ab_idx')],
            },
        ),
    ]
