# Generated by Django 5.2.8 on 2026-06-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technical_seo', '0002_technicalseoaudit_gsc_country_filter_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='technicalseoaudit',
            new_name='technical_s_website_5cd4c2_idx',
            old_name='page_speed__website_7d9537_idx',
        ),
        migrations.RenameIndex(
            model_name='technicalseoaudit',
            new_name='technical_s_request_888f70_idx',
            old_name='page_speed__request_92d8b3_idx',
        ),
        migrations.RenameIndex(
            model_name='technicalseoissue',
            new_name='technical_s_audit_i_5ad5a4_idx',
            old_name='page_speed__audit_i_c09a7f_idx',
        ),
        migrations.RenameIndex(
            model_name='technicalseoissue',
            new_name='technical_s_audit_i_1eedcf_idx',
            old_name='page_speed__audit_i_65c29a_idx',
        ),
        migrations.RenameIndex(
            model_name='technicalseoissue',
            new_name='technical_s_status_671489_idx',
            old_name='page_speed__status_1ad9fd_idx',
        ),
        migrations.RenameIndex(
            model_name='technicalseopage',
            new_name='technical_s_audit_i_ed9060_idx',
            old_name='page_speed__audit_i_a16639_idx',
        ),
        migrations.RenameIndex(
            model_name='technicalseopage',
            new_name='technical_s_audit_i_c8c4e6_idx',
            old_name='page_speed__audit_i_2891eb_idx',
        ),
        migrations.RenameIndex(
            model_name='technicalseowebsite',
            new_name='technical_s_added_b_8f954f_idx',
            old_name='page_speed__added_b_08922a_idx',
        ),
        migrations.AlterModelTable(
            name='technicalseoaudit',
            table='technical_seo_technicalseoaudit',
        ),
        migrations.AlterModelTable(
            name='technicalseoissue',
            table='technical_seo_technicalseoissue',
        ),
        migrations.AlterModelTable(
            name='technicalseopage',
            table='technical_seo_technicalseopage',
        ),
        migrations.AlterModelTable(
            name='technicalseowebsite',
            table='technical_seo_technicalseowebsite',
        ),
    ]
