# Generated by Django 5.2.8 on 2026-06-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_seo', '0003_rename_page_speed__website_7d9537_idx_technical_s_website_5cd4c2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalseoaudit',
            name='pagespeed_desktop',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='technicalseoaudit',
            name='pagespeed_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='technicalseoaudit',
            name='pagespeed_mobile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='technicalseoaudit',
            name='pagespeed_status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
