# Generated by Django 5.2.8 on 2026-07-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technical_seo", "0005_alter_technicalseoaudit_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicalseoaudit",
            name="ai_input_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="technicalseoaudit",
            name="ai_output_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="technicalseoaudit",
            name="ai_total_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
