# Generated by Django 5.2.8 on 2026-06-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.TextField(blank=True, default=""),
        ),
    ]
