# Generated by Django 5.2.8 on 2026-06-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='banner_image',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.TextField(blank=True, default=''),
        ),
    ]
