# Generated by Django 5.2.8 on 2026-07-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_banner_image_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('user', 'User')], max_length=32, unique=True)),
                ('seo_view', models.BooleanField(default=True)),
                ('seo_overview', models.BooleanField(default=True)),
                ('seo_traffic_insights', models.BooleanField(default=True)),
                ('seo_performance_trends', models.BooleanField(default=True)),
                ('analytics_view', models.BooleanField(default=True)),
                ('analytics_overview', models.BooleanField(default=True)),
                ('analytics_traffic_insights', models.BooleanField(default=True)),
                ('analytics_performance_trends', models.BooleanField(default=True)),
                ('automation_view', models.BooleanField(default=True)),
                ('automation_ai_workflows', models.BooleanField(default=True)),
                ('automation_prompt_library', models.BooleanField(default=True)),
                ('automation_automation_rules', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('user', 'User')], default='user', max_length=16),
        ),
    ]
