# Generated by Codex

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SERPAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('target_url', models.URLField(blank=True, max_length=1000)),
                ('competitor_urls', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('target_snapshot', models.JSONField(blank=True, default=dict)),
                ('competitor_snapshots', models.JSONField(blank=True, default=list)),
                ('content_strategies', models.JSONField(blank=True, default=list)),
                ('serp_opportunities', models.JSONField(blank=True, default=list)),
                ('technical_findings', models.JSONField(blank=True, default=list)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('ai_error', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serp_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='serpanalysis',
            index=models.Index(fields=['requested_by', '-started_at'], name='serp_analys_request_e468ea_idx'),
        ),
        migrations.AddIndex(
            model_name='serpanalysis',
            index=models.Index(fields=['status'], name='serp_analys_status_c72b55_idx'),
        ),
        migrations.AddIndex(
            model_name='serpanalysis',
            index=models.Index(fields=['keyword'], name='serp_analys_keyword_d53674_idx'),
        ),
    ]
