# Generated by Django 5.2.8 on 2026-06-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serp_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='serpanalysis',
            new_name='serp_analys_request_744b17_idx',
            old_name='serp_analys_request_e468ea_idx',
        ),
        migrations.RenameIndex(
            model_name='serpanalysis',
            new_name='serp_analys_status_17ec17_idx',
            old_name='serp_analys_status_c72b55_idx',
        ),
        migrations.RenameIndex(
            model_name='serpanalysis',
            new_name='serp_analys_keyword_5f32ea_idx',
            old_name='serp_analys_keyword_d53674_idx',
        ),
    ]