# Generated by Django 5.2.8 on 2026-06-25 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkAltTextAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(max_length=1000)),
                ('page_title', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('total_images', models.PositiveIntegerField(default=0)),
                ('missing_alt_count', models.PositiveIntegerField(default=0)),
                ('generated_alt_count', models.PositiveIntegerField(default=0)),
                ('images_json', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_alt_text_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['requested_by', '-started_at'], name='bulk_alt_te_request_6c0408_idx'), models.Index(fields=['status'], name='bulk_alt_te_status_62bb89_idx')],
            },
        ),
    ]
