# Generated by Django 5.2.1 on 2026-06-18 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPRMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_name', models.CharField(max_length=255)),
                ('competitor_website', models.URLField(max_length=500)),
                ('pricing_url', models.URLField(blank=True, max_length=1000)),
                ('monitored_urls', models.JSONField(blank=True, default=list)),
                ('news_keywords', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_pr_monitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingPRRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('pages_checked', models.PositiveSmallIntegerField(default=0)),
                ('changes_found', models.PositiveSmallIntegerField(default=0)),
                ('news_mentions_found', models.PositiveSmallIntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('ai_error', models.TextField(blank=True)),
                ('ai_prompt_chars', models.PositiveIntegerField(default=0)),
                ('ai_input_tokens', models.PositiveIntegerField(default=0)),
                ('ai_output_tokens', models.PositiveIntegerField(default=0)),
                ('ai_total_tokens', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='pricing_pr_monitor.pricingprmonitor')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_pr_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingPRNewsMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('snippet', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_mentions', to='pricing_pr_monitor.pricingprmonitor')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_mentions', to='pricing_pr_monitor.pricingprrun')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingPRSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('final_url', models.URLField(blank=True, max_length=1000)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('meta_description', models.TextField(blank=True)),
                ('headings', models.JSONField(blank=True, default=list)),
                ('pricing_terms', models.JSONField(blank=True, default=list)),
                ('cta_terms', models.JSONField(blank=True, default=list)),
                ('text_excerpt', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='pricing_pr_monitor.pricingprmonitor')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='pricing_pr_monitor.pricingprrun')),
            ],
            options={
                'ordering': ['url'],
            },
        ),
        migrations.CreateModel(
            name='PricingPRChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('evidence', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='pricing_pr_monitor.pricingprmonitor')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='pricing_pr_monitor.pricingprrun')),
                ('current_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='pricing_pr_monitor.pricingprsnapshot')),
                ('previous_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_changes', to='pricing_pr_monitor.pricingprsnapshot')),
            ],
            options={
                'ordering': ['severity', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pricingprmonitor',
            index=models.Index(fields=['added_by', '-created_at'], name='pricing_pr__added_b_e53e15_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingprmonitor',
            index=models.Index(fields=['is_active'], name='pricing_pr__is_acti_42139c_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingprrun',
            index=models.Index(fields=['monitor', '-started_at'], name='pricing_pr__monitor_6522c9_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingprrun',
            index=models.Index(fields=['requested_by', '-started_at'], name='pricing_pr__request_95cbd8_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingprrun',
            index=models.Index(fields=['status'], name='pricing_pr__status_d163e0_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingprnewsmention',
            index=models.Index(fields=['run'], name='pricing_pr__run_id_2a1830_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingprnewsmention',
            index=models.Index(fields=['monitor', '-published_at'], name='pricing_pr__monitor_6f84db_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingprnewsmention',
            index=models.Index(fields=['keyword'], name='pricing_pr__keyword_56dd27_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingprsnapshot',
            index=models.Index(fields=['monitor', 'url', '-checked_at'], name='pricing_pr__monitor_bd180d_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingprsnapshot',
            index=models.Index(fields=['run'], name='pricing_pr__run_id_5dcee8_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingprsnapshot',
            index=models.Index(fields=['content_hash'], name='pricing_pr__content_cb2940_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingprchange',
            index=models.Index(fields=['run', 'severity'], name='pricing_pr__run_id_8a67cc_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingprchange',
            index=models.Index(fields=['monitor', '-created_at'], name='pricing_pr__monitor_bc9ee8_idx'),
        ),
    ]
