# Generated by Django 5.2.1 on 2026-06-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_pr_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingprnewsmention',
            name='competitive_impact',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pricingprnewsmention',
            name='mention_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pricingprnewsmention',
            name='relevance_reason',
            field=models.TextField(blank=True),
        ),
    ]
