# Generated by Django 5.2.1 on 2026-06-18 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField(max_length=500)),
                ('target_location', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('seed_topic', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_research_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeywordResearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('max_pages', models.PositiveSmallIntegerField(default=20)),
                ('pages_crawled', models.PositiveSmallIntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('ai_error', models.TextField(blank=True)),
                ('planner_status', models.CharField(blank=True, max_length=100)),
                ('planner_error', models.TextField(blank=True)),
                ('ai_prompt_chars', models.PositiveIntegerField(default=0)),
                ('ai_input_tokens', models.PositiveIntegerField(default=0)),
                ('ai_output_tokens', models.PositiveIntegerField(default=0)),
                ('ai_total_tokens', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='keyword_research.keywordresearchproject')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_research_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='KeywordResearchPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('meta_description', models.TextField(blank=True)),
                ('h1', models.JSONField(blank=True, default=list)),
                ('h2', models.JSONField(blank=True, default=list)),
                ('h3', models.JSONField(blank=True, default=list)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('top_terms', models.JSONField(blank=True, default=list)),
                ('content_excerpt', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='keyword_research.keywordresearchrun')),
            ],
            options={
                'ordering': ['url'],
            },
        ),
        migrations.CreateModel(
            name='KeywordPlannerMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('avg_monthly_searches', models.PositiveIntegerField(blank=True, null=True)),
                ('competition', models.CharField(blank=True, max_length=100)),
                ('competition_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('low_top_of_page_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('high_top_of_page_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(default='google_keyword_planner', max_length=100)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_metrics', to='keyword_research.keywordresearchrun')),
            ],
            options={
                'ordering': ['keyword'],
            },
        ),
        migrations.CreateModel(
            name='KeywordIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('intent', models.CharField(blank=True, max_length=100)),
                ('funnel_stage', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(blank=True, max_length=20)),
                ('suggested_page', models.CharField(blank=True, max_length=500)),
                ('content_angle', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('source', models.CharField(default='ai', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_ideas', to='keyword_research.keywordresearchrun')),
            ],
            options={
                'ordering': ['priority', 'keyword'],
            },
        ),
        migrations.CreateModel(
            name='KeywordCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=255)),
                ('intent', models.CharField(blank=True, max_length=100)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('recommended_page_type', models.CharField(blank=True, max_length=255)),
                ('recommended_action', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='keyword_research.keywordresearchrun')),
            ],
            options={
                'ordering': ['cluster_name'],
            },
        ),
        migrations.AddIndex(
            model_name='keywordresearchproject',
            index=models.Index(fields=['added_by', '-created_at'], name='keyword_res_added_b_412350_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordresearchrun',
            index=models.Index(fields=['project', '-started_at'], name='keyword_res_project_1ec84e_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordresearchrun',
            index=models.Index(fields=['requested_by', '-started_at'], name='keyword_res_request_3fecbb_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordresearchrun',
            index=models.Index(fields=['status'], name='keyword_res_status_47b37c_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordresearchpage',
            index=models.Index(fields=['run'], name='keyword_res_run_id_54ce0a_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordplannermetric',
            index=models.Index(fields=['run'], name='keyword_res_run_id_2020f8_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordplannermetric',
            index=models.Index(fields=['keyword'], name='keyword_res_keyword_12e7e6_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordidea',
            index=models.Index(fields=['run'], name='keyword_res_run_id_bd53d2_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordidea',
            index=models.Index(fields=['keyword'], name='keyword_res_keyword_275332_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordcluster',
            index=models.Index(fields=['run'], name='keyword_res_run_id_6e81ee_idx'),
        ),
    ]
