# Generated by Django 5.2.1 on 2026-06-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordresearchproject',
            name='seed_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='keywordresearchproject',
            name='website_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
