# Generated by Django 5.2.1 on 2026-06-18 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentGapProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField(max_length=500)),
                ('target_topic', models.CharField(blank=True, max_length=255)),
                ('target_market', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_gap_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentGapAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('own_url', models.URLField(max_length=1000)),
                ('competitor_urls', models.JSONField(blank=True, default=list)),
                ('own_page_snapshot', models.JSONField(blank=True, default=dict)),
                ('competitor_snapshots', models.JSONField(blank=True, default=list)),
                ('content_gaps', models.JSONField(blank=True, default=list)),
                ('keyword_opportunities', models.JSONField(blank=True, default=list)),
                ('recommended_sections', models.JSONField(blank=True, default=list)),
                ('execution_plan', models.JSONField(blank=True, default=list)),
                ('wireframe', models.JSONField(blank=True, default=dict)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('ai_error', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_gap_analyses', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='content_gap.contentgapproject')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contentgapproject',
            index=models.Index(fields=['added_by', '-created_at'], name='content_gap_added_b_832b49_idx'),
        ),
        migrations.AddIndex(
            model_name='contentgapanalysis',
            index=models.Index(fields=['project', '-started_at'], name='content_gap_project_6aebfa_idx'),
        ),
        migrations.AddIndex(
            model_name='contentgapanalysis',
            index=models.Index(fields=['requested_by', '-started_at'], name='content_gap_request_f05b02_idx'),
        ),
        migrations.AddIndex(
            model_name='contentgapanalysis',
            index=models.Index(fields=['status'], name='content_gap_status_7b35c9_idx'),
        ),
    ]
