# Generated by Django 5.2.1 on 2026-06-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_gap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentgapanalysis',
            name='ai_input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contentgapanalysis',
            name='ai_output_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contentgapanalysis',
            name='ai_prompt_chars',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contentgapanalysis',
            name='ai_total_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
