# Generated by Django 5.2.8 on 2026-06-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_speed_and_cwv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
