# Generated by Django 5.2.8 on 2026-06-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_speed_and_cwv', '0002_website_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
