# Generated by Django 5.2.8 on 2026-06-16 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_speed_and_cwv', '0003_website_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSpeedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], max_length=20)),
                ('performance_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('accessibility_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('best_practices_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seo_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('first_contentful_paint', models.DecimalField(blank=True, decimal_places=2, help_text='Seconds', max_digits=8, null=True)),
                ('largest_contentful_paint', models.DecimalField(blank=True, decimal_places=2, help_text='Seconds', max_digits=8, null=True)),
                ('interaction_to_next_paint', models.DecimalField(blank=True, decimal_places=2, help_text='Milliseconds', max_digits=8, null=True)),
                ('cumulative_layout_shift', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('total_blocking_time', models.DecimalField(blank=True, decimal_places=2, help_text='Milliseconds', max_digits=8, null=True)),
                ('speed_index', models.DecimalField(blank=True, decimal_places=2, help_text='Seconds', max_digits=8, null=True)),
                ('time_to_first_byte', models.DecimalField(blank=True, decimal_places=2, help_text='Seconds', max_digits=8, null=True)),
                ('raw_response_json', models.JSONField(blank=True, default=dict)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speed_reports', to='page_speed_and_cwv.website')),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['website', 'device_type', '-scanned_at'], name='page_speed__website_b906b8_idx')],
            },
        ),
    ]
