# Generated by Django 5.2.8 on 2026-06-16 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_speed_and_cwv', '0004_websitespeedreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSpeedReportAiIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speed_report_ai_indexes', to='page_speed_and_cwv.website')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.AddField(
            model_name='websitespeedreport',
            name='report_ai_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='page_speed_and_cwv.websitespeedreportaiindex'),
        ),
        migrations.AddIndex(
            model_name='websitespeedreportaiindex',
            index=models.Index(fields=['website', '-scanned_at'], name='page_speed__website_ecd397_idx'),
        ),
    ]
