# Generated by Django 5.2.1 on 2026-06-17 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_existing_audit_websites(apps, schema_editor):
    Website = apps.get_model('page_speed_and_cwv', 'Website')
    TechnicalSEOAudit = apps.get_model('page_speed_and_cwv', 'TechnicalSEOAudit')
    TechnicalSEOWebsite = apps.get_model('page_speed_and_cwv', 'TechnicalSEOWebsite')

    website_ids = TechnicalSEOAudit.objects.values_list('website_id', flat=True).distinct()
    for website in Website.objects.filter(id__in=website_ids):
        TechnicalSEOWebsite.objects.get_or_create(
            id=website.id,
            defaults={
                'website_url': website.website_url,
                'note': website.note,
                'added_by_id': website.added_by_id,
                'is_active': website.is_active,
                'date_added': website.date_added,
                'date_modified': website.date_modified,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('page_speed_and_cwv', '0006_technicalseoaudit_technicalseopage_technicalseoissue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSEOWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField(max_length=500)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_seo_websites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.RunPython(copy_existing_audit_websites, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='technicalseoaudit',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_seo_audits', to='page_speed_and_cwv.technicalseowebsite'),
        ),
        migrations.AddIndex(
            model_name='technicalseowebsite',
            index=models.Index(fields=['added_by', '-date_added'], name='page_speed__added_b_08922a_idx'),
        ),
    ]
