# Generated by Django 5.2.8 on 2026-06-24 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_speed_and_cwv', '0008_move_technical_seo_models_to_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='page_speed_and_cwv.website')),
            ],
            options={
                'ordering': ['-date_added'],
                'indexes': [models.Index(fields=['website', 'page_url'], name='page_speed__website_542879_idx')],
            },
        ),
    ]
