# Generated by Django 5.2.8 on 2026-06-24 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_speed_and_cwv', '0009_websitepage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsitePageDiscoveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_summary', models.CharField(blank=True, help_text='Summary of sources used, for example sitemap, robots, homepage.', max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_speed_page_discovery_runs', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_discovery_runs', to='page_speed_and_cwv.website')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='WebsitePageDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(max_length=500)),
                ('source', models.CharField(blank=True, help_text='Discovery source, for example sitemap, robots, or homepage.', max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_speed_page_discoveries', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_discoveries', to='page_speed_and_cwv.website')),
                ('discovery_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_pages', to='page_speed_and_cwv.websitepagediscoveryrun')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.AddIndex(
            model_name='websitepagediscoveryrun',
            index=models.Index(fields=['website', '-date_added'], name='page_speed__website_1f0db0_idx'),
        ),
        migrations.AddIndex(
            model_name='websitepagediscovery',
            index=models.Index(fields=['website', '-date_added'], name='page_speed__website_617555_idx'),
        ),
        migrations.AddIndex(
            model_name='websitepagediscovery',
            index=models.Index(fields=['website', 'page_url'], name='page_speed__website_86c9c6_idx'),
        ),
    ]
