# Generated by Django 5.2.8 on 2026-06-25 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_speed_and_cwv', '0010_websitepagediscoveryrun_websitepagediscovery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitespeedreportaiindex',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speed_report_ai_indexes', to='page_speed_and_cwv.websitepage'),
        ),
        migrations.AddIndex(
            model_name='websitespeedreportaiindex',
            index=models.Index(fields=['page', '-scanned_at'], name='page_speed__page_id_75bb21_idx'),
        ),
    ]
