# Generated by Django 5.2.8 on 2026-06-25 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_speed_and_cwv', '0011_websitespeedreportaiindex_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitespeedreport',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speed_reports', to='page_speed_and_cwv.websitepage'),
        ),
        migrations.AddIndex(
            model_name='websitespeedreport',
            index=models.Index(fields=['page', 'device_type', '-scanned_at'], name='page_speed__page_id_a74ed6_idx'),
        ),
    ]
