# Generated by Django 5.2.8 on 2026-06-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_speed_and_cwv', '0012_websitespeedreport_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitespeedreportaiindex',
            name='scan_group_token',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddIndex(
            model_name='websitespeedreportaiindex',
            index=models.Index(fields=['website', 'scan_group_token'], name='page_speed__website_a054e1_idx'),
        ),
    ]
