# Generated by Django 5.2.8 on 2026-06-25 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_speed_and_cwv', '0013_websitespeedreportaiindex_scan_group_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSpeedReportAiEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('improvements_json', models.JSONField(blank=True, default=list)),
                ('declines_json', models.JSONField(blank=True, default=list)),
                ('warnings_json', models.JSONField(blank=True, default=list)),
                ('recommendations_json', models.JSONField(blank=True, default=list)),
                ('raw_ai_response_json', models.JSONField(blank=True, default=dict)),
                ('ai_error', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('latest_report_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_ai_evaluations', to='page_speed_and_cwv.websitespeedreportaiindex')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speed_report_ai_evaluations', to='page_speed_and_cwv.websitepage')),
                ('previous_report_index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_ai_evaluations', to='page_speed_and_cwv.websitespeedreportaiindex')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speed_report_ai_evaluations', to='page_speed_and_cwv.website')),
            ],
            options={
                'ordering': ['-date_added'],
                'indexes': [models.Index(fields=['website', '-date_added'], name='page_speed__website_d4dc92_idx'), models.Index(fields=['page', '-date_added'], name='page_speed__page_id_ef0272_idx'), models.Index(fields=['latest_report_index'], name='page_speed__latest__91b0b9_idx')],
            },
        ),
    ]
